# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CiBER-Seq
tagline:          'CRISPRi with Barcode Expression Reporters'
description:      'CRISPR interference with barcode expression reporter sequencing'
url:              https://ingolia-lab.github.io/CiBER_seq/

author:
  name:           'Nicholas Ingolia'
  url:            https://ingolia-lab.org/

github:
  repo:           https://github.com/ingolia-lab/CiBER_seq/